language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
os: linux
cache: cargo

script:
- cargo test --all
- if [[ $TRAVIS_RUST_VERSION = stable ]]; then cargo doc --all; fi

deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: target/doc
  keep-history: false
  on:
    branch: master
    condition: $TRAVIS_RUST_VERSION = stable
